environment:
  matrix:
  - nodejs_version: "6"
  - nodejs_version: "7"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Post-install test scripts.
test_script:
  - npm test

# Don't actually build.
build: off
